services:
  - type: web
    name: heatbox-portal
    env: docker
    branch: main
    buildCommand: docker build -t render-web .
    startCommand: sh -lc "python manage.py migrate --noinput && gunicorn civictrack_project.wsgi --bind 0.0.0.0:8000 --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "replace-with-your-secret"
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
        sync: false
      - key: DATABASE_URL
        value: ""
        sync: false
    plan: free
    autoDeploy: true
